require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PeopleGroupsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PeopleGroup. As you add validations to PeopleGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PeopleGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all people_groups as @people_groups" do
      people_group = PeopleGroup.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:people_groups)).to eq([people_group])
    end
  end

  describe "GET #show" do
    it "assigns the requested people_group as @people_group" do
      people_group = PeopleGroup.create! valid_attributes
      get :show, {:id => people_group.to_param}, valid_session
      expect(assigns(:people_group)).to eq(people_group)
    end
  end

  describe "GET #new" do
    it "assigns a new people_group as @people_group" do
      get :new, {}, valid_session
      expect(assigns(:people_group)).to be_a_new(PeopleGroup)
    end
  end

  describe "GET #edit" do
    it "assigns the requested people_group as @people_group" do
      people_group = PeopleGroup.create! valid_attributes
      get :edit, {:id => people_group.to_param}, valid_session
      expect(assigns(:people_group)).to eq(people_group)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PeopleGroup" do
        expect {
          post :create, {:people_group => valid_attributes}, valid_session
        }.to change(PeopleGroup, :count).by(1)
      end

      it "assigns a newly created people_group as @people_group" do
        post :create, {:people_group => valid_attributes}, valid_session
        expect(assigns(:people_group)).to be_a(PeopleGroup)
        expect(assigns(:people_group)).to be_persisted
      end

      it "redirects to the created people_group" do
        post :create, {:people_group => valid_attributes}, valid_session
        expect(response).to redirect_to(PeopleGroup.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved people_group as @people_group" do
        post :create, {:people_group => invalid_attributes}, valid_session
        expect(assigns(:people_group)).to be_a_new(PeopleGroup)
      end

      it "re-renders the 'new' template" do
        post :create, {:people_group => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested people_group" do
        people_group = PeopleGroup.create! valid_attributes
        put :update, {:id => people_group.to_param, :people_group => new_attributes}, valid_session
        people_group.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested people_group as @people_group" do
        people_group = PeopleGroup.create! valid_attributes
        put :update, {:id => people_group.to_param, :people_group => valid_attributes}, valid_session
        expect(assigns(:people_group)).to eq(people_group)
      end

      it "redirects to the people_group" do
        people_group = PeopleGroup.create! valid_attributes
        put :update, {:id => people_group.to_param, :people_group => valid_attributes}, valid_session
        expect(response).to redirect_to(people_group)
      end
    end

    context "with invalid params" do
      it "assigns the people_group as @people_group" do
        people_group = PeopleGroup.create! valid_attributes
        put :update, {:id => people_group.to_param, :people_group => invalid_attributes}, valid_session
        expect(assigns(:people_group)).to eq(people_group)
      end

      it "re-renders the 'edit' template" do
        people_group = PeopleGroup.create! valid_attributes
        put :update, {:id => people_group.to_param, :people_group => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested people_group" do
      people_group = PeopleGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => people_group.to_param}, valid_session
      }.to change(PeopleGroup, :count).by(-1)
    end

    it "redirects to the people_groups list" do
      people_group = PeopleGroup.create! valid_attributes
      delete :destroy, {:id => people_group.to_param}, valid_session
      expect(response).to redirect_to(people_groups_url)
    end
  end

end
